#!/bin/bash

RESP="$(docker exec -it ollama echo "allgood" 2>/dev/null)"

if [[ ! "$RESP" == 'allgood' ]]; then
	docker container start ollama &>/dev/null;
fi

docker exec -it ollama ollama $@ 2>/dev/null
